[neovim]
source = "nvim"
[neovim.windows]
target_path = "%LOCALAPPDATA%/nvim/"
[neovim.unix]
target_path = "$XDG_CONFIG_HOME/nvim/"

[wezterm]
source = "wezterm"
[wezterm.windows]
target_path = "%USERPROFILE%/.config/wezterm/"
[wezterm.unix]
target_path = "$XDG_CONFIG_HOME/wezterm/"

[nushell]
source = "nushell"
[nushell.windows]
target_path = "%APPDATA%/nushell/"
[nushell.unix]
target_path = "$XDG_CONFIG_HOME/nushell/"

[git]
source = "git"
[git.windows]
target_path = "%USERPROFILE%/.config/git/"
[git.unix]
target_path = "$XDG_CONFIG_HOME/git/"